stages:
  - build
  - release


variables:
  MOODLE_PACKAGE_NAME: "theme_defensoriapublico"
  ARCHIVE_DIR: "${CI_PROJECT_DIR}/archive"
  THEME_FILE_NAME: "${MOODLE_PACKAGE_NAME}-${CI_COMMIT_TAG}.zip"
  THEME_FILE_PATH: "${ARCHIVE_DIR}/${THEME_FILE_NAME}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${MOODLE_PACKAGE_NAME}/${CI_COMMIT_TAG}"
  THEME_URL: "${PACKAGE_REGISTRY_URL}/${THEME_FILE_NAME}"


build and upload:
  image: alpine:latest
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apk add --update --no-cache zip curl
    - mkdir -p "${ARCHIVE_DIR}"
    - cp README.md LICENSE.md src/
    - cd src && zip -r "${THEME_FILE_PATH}" .
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "${THEME_FILE_PATH}" "${THEME_URL}"


release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" \
      --assets-link "{\"name\":\"${THEME_FILE_NAME}\",\"url\":\"${THEME_URL}\"}"
