name: Build Release Package

on:
  push:
    tags:
      - 'v[0-9]*'
      - 'v[0-9]*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Copy README and LICENSE files
        run: cp *.md src/

      - name: Bundle Theme
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: '../theme_defensoriapublico.zip'
          directory: 'src'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "theme_defensoriapublico.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

